### ISSUE TITLE
Make with params.mk crates __init__.py

### ISSUE THREAD

**Issue by rayoogmy** [gridengine/drmaa2-python#1]
Hi there,

Just trying to make the project from a fresh clone.

Upon running make,  `__version__` gets set to ` 8.6.8` which is clearly not a valid number nor a proper string. 

Latest source code has it set to `__version__ = '8.7.0a0'` in __init__.py. Setting the variable in params.mk to  `"'8.7.0a0'"` fixes the issue.

**Comment by rayoogmy** [comment]
This was done with python3, using venv.

**Comment by alea55** [comment]
Makefile has been fixed meanwhile...
