### ISSUE TITLE
Linking error on UGE 8.6.7

### ISSUE THREAD

**Issue by joemathai** [gridengine/drmaa2-python#3]
Hi, I get the following error when I try to run print(drmaa2.get_drmaa_name()) 

uge_root/lib/lx-amd64/libdrmaa2.so: undefined symbol: uge_vi_impl_spec_get

**Comment by alea55** [comment]
there seems to be some version inconsistency between your used libdrmaa2.so and the corresponding drmaa2-python version you are using...

you can verify this by checking the following:
nm $SGE_ROOT/lib/lx-amd64/libdrmaa2.so | grep uge_vi_impl_spec_get
and the corresponding python files
drmaa2/version.py
82:                cls.get_drmaa2_library().uge_vi_impl_spec_get(ctypes_version))

drmaa2/library_manager.py
217:        drmaa2_lib.uge_vi_impl_spec_get.restype = drmaa2_dict
218:        drmaa2_lib.uge_vi_impl_spec_get.argtypes = [POINTER(drmaa2_version)]

solution is to upgrade UGE to a newer patch release (highly recommended) or to go back to an older drmaa2-python version (that does not contain above lines or simply comment them out, not recommended)

**Comment by joemathai** [comment]
please note that the repo states compatibility from 8.6.0 onwards, it might be a good idea to update the readme

**Comment by alea55** [comment]
thanks for pointing out... I'll change it
